### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files

### ISSUE THREAD

**Issue by alialrabi** [bshao001/ChatLearner#25]
Hi,Thanks for your great project.
I have deployed trainer and finished fine ,but when start to run botui.py I get the folloing error.
Result folder just have the file  /Data/Result/train_log/events.out.tfevents.1516479132.ali ,no file with name basic.
 

/home/ali/PycharmProjects/ChatLearner/venv/bin/python /home/ali/PycharmProjects/ChatLearner/chatbot/botui.py
/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)# Prepare dataset placeholder and hyper parameters ...# Loading hparams from /home/ali/PycharmProjects/ChatLearner/Data/Corpus/hparams.json ...
Creating inference model ...
 Building graph for the model ...
 Restoring model weights ...
Traceback (most recent call last):
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/ali/PycharmProjects/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/botui.py", line 53, in <module>
    bot_ui()
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/botui.py", line 32, in bot_ui
    result_dir=res_dir, result_file='basic')
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/botpredictor.py", line 62, in __init__
    self.model.saver.restore(session, os.path.join(result_dir, result_file))
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/ali/PycharmProjects/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/botui.py", line 53, in <module>
    bot_ui()
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/botui.py", line 32, in bot_ui
    result_dir=res_dir, result_file='basic')
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/botpredictor.py", line 59, in __init__
    batch_input=self.infer_batch)
  File "/home/ali/PycharmProjects/ChatLearner/chatbot/modelcreator.py", line 103, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/ali/PycharmProjects/ChatLearner/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/ali/PycharmProjects/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Process finished with exit code 1

**Comment by bshao001** [comment]
@alialrabi 

The files generated by the trainer have the epoch numbers in the names. Please go to /Data/Result folder and rename them by removing the epoch numbers.

Hope this helps.
