### ISSUE TITLE
Too Many Error In your Code.

### ISSUE THREAD

**Issue by jinfagang** [bshao001/ChatLearner#3]
No defense but your code are such mass. First when I run `cd chatbot && python3 bottrainner.py` it says:
```
Traceback (most recent call last):
  File "bottrainer.py", line 20, in <module>
    from chatbot.tokenizeddata import TokenizedData
ModuleNotFoundError: No module named 'chatbot'
```
So I run `python3 chatbot/bottrainer.py` then it says:
```
self.text_set = self.text_set.concatenate(src_tgt_dataset)
AttributeError: 'RepeatDataset' object has no attribute 'concatenate'
```
obviously, this is totally nonsense line of:
```
self.text_set = self.text_set.concatenate(src_tgt_dataset)
```
I uncomment the concatenate line, and it goes this error:
```
Traceback (most recent call last):
  File "chatbot/bottrainer.py", line 142, in <module>
    bt = BotTrainer(corpus_dir=corp_dir)
  File "chatbot/bottrainer.py", line 30, in __init__
    tokenized_data = TokenizedData(corpus_dir=corpus_dir)
  File "/Volumes/xs/CodeSpace/ng/ai/experiment/ChatLearner/chatbot/tokenizeddata.py", line 72, in __init__
    self._convert_to_tokens(buffer_size)
  File "/Volumes/xs/CodeSpace/ng/ai/experiment/ChatLearner/chatbot/tokenizeddata.py", line 249, in _convert_to_tokens
    output_buffer_size=buffer_size)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 813, in map
    return MapDataset(self, map_func, num_threads, output_buffer_size)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1436, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 619, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/framework/function.py", line 167, in _create_definition_if_needed
    outputs = self._func(*inputs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1422, in tf_map_func
    ret = map_func(*nested_args)
  File "/Volumes/xs/CodeSpace/ng/ai/experiment/ChatLearner/chatbot/tokenizeddata.py", line 248, in <lambda>
    (self.case_table.lookup(src), self.case_table.lookup(tgt)),
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/lookup/lookup_ops.py", line 186, in lookup
    self._table_ref, key_tensor, self._default_value, name=scope)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_lookup_ops.py", line 288, in _lookup_table_find
    name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/framework/function.py", line 81, in create_op
    data_types, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 361, in create_op
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1250, in __init__
    input_types))
TypeError: In op 'hash_table_Lookup', input types ([tf.string, tf.string, tf.string]) are not compatible with expected types ([tf.string_ref, tf.string, tf.string])
```

I have no idea how you write your code, but this is really not worth to waste time on this buggy project.

**Comment by bshao001** [comment]
Do you have an environment variable PYTHONPATH setup? I ran this in Windows, and if the project root is C:\Python\ChatLearner, I set PYTHONPATH to be: C:\Python\ChatLearner. This way, any relative module import (modules inside this project) should work.

Please let me know if you see any other problems after that.

**Comment by bshao001** [comment]
@jinfagang , no problem. Please let me know if you see any other issues.
